version: '3.7'
services:
  wordpress:
    container_name: ${WORDPRESS_CONTAINER}
    build: ./.docker/
    depends_on:
      - mysql
    restart: always
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_CONTAINER}_db"
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_DEBUG: 'false'
      VIRTUAL_HOST: ${HOSTS}
      VIRTUAL_PORT: ${PORTO}
    volumes: &ref_0
      - ./public:/var/www/html
      - ./assets/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./assets/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini

  mysql:
    image: mysql:5.7
    container_name: "${WORDPRESS_CONTAINER}_db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./assets/mysql/dump:/dump
      - ./assets/mysql/data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - ${SMTP_PORT}:1025
      - ${MAILHOG_PORT}:8025

volumes: {}

networks:
  default:
    external:
      name: nginx-proxy
