<?php
/**
 * Do not edit this file.
 */

if ( version_compare( phpversion(), '5.5.0', '<' ) ) {
	die( 'Execution aborted because PHP Version is lower than 5.5.0' );
}

// Actual wp-config.php lies one level above.
require_once dirname( __DIR__ ) . '/wp-config.php';
