<?php
define('WP_CACHE', true); // Added by WP Rocket

/**
 * Do not edit this file.
 */

if ( version_compare( phpversion(), '7.0', '<' ) ) {
	die( 'Execution aborted because PHP Version is lower than 7.0' );
}

/**=========================================================================
 * Load local configuration if available
 * Create a local-config.php file to override any of the following constants
 **=========================================================================*/
if ( file_exists(dirname( __FILE__ ) . '/local-config.php' ) ) {
	include( dirname(__FILE__ ) . '/local-config.php' );
}

/**=================================================================================================
 * WordPress environments
 * Manage different environments for your installation to define development constants automatically
 **=================================================================================================*/
$envs = array( 'development', 'staging', 'production' );
define( 'ENVIRONMENTS', serialize( $envs ) );
if( !defined( 'WP_ENV' ) )
{
  define( 'WP_ENV', 'production' );
}

/**=================================================================================
 * Database credentials and setup
 * This login data is required to access the WordPress database. Keep them a secret!
 **=================================================================================*/
if( !defined( 'DB_NAME' ) )
{
	define('DB_NAME', 'd01c4312' );
}
if( !defined( 'DB_USER' ) )
{
	define( 'DB_USER', 'd01c4312' );
}
if( !defined( 'DB_PASSWORD' ) )
{
	define('DB_PASSWORD', 'qfEE7woSrKPxYdLF' );
}
if( !defined( 'DB_HOST' ) )
{
	define( 'DB_HOST', 'localhost' );
}
if( !isset( $table_prefix ) )
{
	$table_prefix  = 'wpit24_';
}

/**==============================================
 * Database charset and collation
 * You most certainly don't wanna change these...
 **==============================================*/
if( !defined( 'DB_CHARSET' ) )
{
	define( 'DB_CHARSET', 'utf8' );
}
if( !defined( 'DB_COLLATE' ) )
{
	define( 'DB_COLLATE', '' );
}

/**======================================================================
 * Authentication keys, for security reasons
 * You can grab these from: https://api.wordpress.org/secret-key/1.1/salt
 **======================================================================*/
define('AUTH_KEY',         'SJ8=K-{?zHxNi*Lb=_Q=Dw# K,P>qfv^ -qs~otEQu;M+7q40z-6$~!+cT9.,scM');
define('SECURE_AUTH_KEY',  '=0,N3;[l+PCCL1OU/u$F/h#%=}Y[OKwT<!-cw0=uw+d`0`9jip5fv;FDU/x0c-bF');
define('LOGGED_IN_KEY',    'NLTt[ve_GNGNXZyk;pd-LU}H:!Ie46*+k((Z6&b{9)W{XdE|`}eH~WYxePdq3=tv');
define('NONCE_KEY',        '+JXl_+sVzuTRYrYAK#A)X2[H0(E8<e^x+u2:wfB>{A3C?R(a;7lSEv0{|PtYYw7H');
define('AUTH_SALT',        'SKivK:nr)?q3ZA(-u|x!2{o)vLLe1O)`(-1f%yL~j<dGY@?jNG?q)|%`-UJ5-`ZA');
define('SECURE_AUTH_SALT', 'Lm?]fm%:jxgaLu|p]N.0N+c7:OK-[a#uR1b0B[+jwDn;Pk6POqgr`-j`gPC]+}E.');
define('LOGGED_IN_SALT',   '+>@w8$v[9X|yg`MT0}wSV:@>jNY?|`bfw31-sArt5VRaJq=A4@fq>k<e|-nB09L,');
define('NONCE_SALT',       '|J!no9A]Am#UQKCXQcR]y<2E4-;*zs9@~5KbsxFpn|=@161uD{]$f:UBw|=+Y)Gy');

/**===================================================
 * Directory and URL configuration
 * These constants ensure a proper directory structure
 **===================================================*/
if( !defined( 'WP_HOME' ) )
{
	define( 'WP_HOME', 'https://www.energieausweis-online-erstellen.de' );
}
if( !defined( 'WP_SITEURL' ) )
{
	define( 'WP_SITEURL', rtrim( WP_HOME, '/' ) . '/core' );
}
if( !defined( 'WP_CONTENT_DIR' ) )
{
	define( 'WP_CONTENT_DIR', dirname(__FILE__) . '/app' );
}
if( !defined( 'WP_CONTENT_URL' ) )
{
	define( 'WP_CONTENT_URL', rtrim( WP_HOME, '/' ) . '/app' );
}

// define( 'FORCE_SSL_ADMIN', true );

/**======================================================================================
 * Core bundled plugins / themes
 * This option toggles whether bundled plugins / themes are downloaded with core upgrades
 **======================================================================================*/
if( !defined( 'CORE_UPGRADE_SKIP_NEW_BUNDLED' ) )
{
	define( 'CORE_UPGRADE_SKIP_NEW_BUNDLED', true );
}

if ( !defined( 'WP_DEFAULT_THEME' ) )
{
	define( 'WP_DEFAULT_THEME', 'immoticket-energieausweis' );
}

define( 'WP_SENTRY_DSN', 'https://d4688837372c4116aaa3361e644cf448@sentry.io/4574452' );
define( 'WP_SENTRY_ERROR_TYPES', E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_USER_DEPRECATED );


/**======================================================================================
 * Environment setup
 * The following constants are setup automatically according to the specified environment
 **======================================================================================*/
switch( WP_ENV )
{
  case 'development':
    define( 'WP_DEBUG', true );
    define( 'WP_DEBUG_LOG', dirname( dirname( __FILE__ ) ) . '/debug.log' );
    define( 'WP_DEBUG_DISPLAY', false );
    define( 'SAVEQUERIES', true );
    define( 'SCRIPT_DEBUG', true );
    define( 'CONCATENATE_SCRIPTS', false );
    define( 'DISALLOW_FILE_EDIT', false );
    break;
  case 'staging':
    define( 'WP_DEBUG', true );
	define( 'WP_DEBUG_LOG', dirname( dirname( __FILE__ ) ) . '/debug.log' );
    define( 'WP_DEBUG_DISPLAY', false );
    define( 'DISALLOW_FILE_EDIT', true );
    break;
  case 'production':
  default:
    define( 'WP_DEBUG', false );
	define( 'WP_DEBUG_LOG', dirname( dirname( __FILE__ ) ) . '/debug.log' );
    define( 'WP_DEBUG_DISPLAY', false );
    define( 'DISALLOW_FILE_EDIT', true );
    break;
}

define( 'DISABLE_WP_CRON', true );

define( 'CF7_MAILCHIMP_API_KEY', '97915031f990d58d79191ac983402b40-us10' );

define( 'EDD_KLICKTIPP_USERNAME', 'bokobat' );
define( 'EDD_KLICKTIPP_PASSWORD', 'HerrArntz' );
define( 'EDD_KLICKTIPP_LIST_ID', 94806 );
define( 'EDD_KLICKTIPP_TAG_ID', 2001353 );

/**===============================
 * WordPress Bootstrap
 * Never edit the following lines!
 **===============================*/
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/core/');

require_once(ABSPATH . 'wp-settings.php');
