wp search-replace "2021.energieausweis-online-erstellen.de" "enon.test"
wp search-replace "www.energieausweis-online-erstellen.de" "enon.test"
wp search-replace "staging.energieausweis.de" "enon.test"
wp search-replace "energieausweis-online-erstellen.de" "enon.test"
wp search-replace "energieausweis.de" "enon.test"
