name: Deploy on staging.energieausweis-online-erstellen.de

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remote Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script:
          ls -la
          cd ./staging.energieausweis-online-erstellen.de
          composer update