name: Deploy to staging

on:
  push:
    branches:
      - staging

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Remote Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script_stop: true
        script: |
          cd /www/htdocs/w012900a/staging.energieausweis-online-erstellen.de/
          ls -la
          composer update